<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Zend Tickets WebApp');
echo $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/style.css'); ?>
	</head>
	<body>
		<div class="header">
			<p><?php echo strip_tags($this->headTitle()); ?> /
			<a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'index'));?>">Home</a> / 
			<a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'new'));?>">Create a ticket</a></p>
		</div>
		<div id="content">
			<?php echo $this->layout()->content; ?>
		</div>
	</body>
</html>